config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "toppages#index"
  resources :toppages, only: [:index]
  resources :users, only: [:edeit, :update, :show]
  resources :posts do
    collection do
      get 'user_posts'
      get 'category_posts'
      get 'maker_posts'
    end
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  resources :categories, only: [:index]
  resources :makers, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, dependent: :destroy
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, :image, :text, :maker_id, :category_id, presence: true
  belongs_to :user
  belongs_to :category
  belongs_to :maker
  has_many :comments,foreign_key: :post_id, dependent: :destroy
  def self.search(search)
    return Post.all unless search
    Post.where('text LIKE(?)', "%#{search}%").or(Post.where('title LIKE(?)', "%#{search}%"))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    comment = @post.comments.build(comment_params)
    if comment.save!
      redirect_to "/posts/#{comment.post_id}"
    else
      @comments = @post.comments.includes(:user).limit(8).order('id DESC').page(params[:page]).per(5)
      @comment = Comment.new(comment_params)
      render "posts/show" 
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController

  def index
    @makers = Maker.all
  end

  def show
    @makers = Maker.limit(8).order('id DESC')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search, :user_posts, :category_posts, :maker_posts]
  def index
    @posts = Post.includes(:user).limit(8).order('id DESC').page(params[:page]).per(8)
  end

  def new
    @post = Post.new
    
  end

  def create
    @post = Post.create(post_params)
    post = Post.new(post_params)
    if post.save
      render :create
    else
      flash.now[:notice] = '入力は全て必須です'
      render "posts/new"
    end
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).limit(8).order('id DESC').page(params[:page]).per(5)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: '投稿を更新しました'
    else
      render :edit
    end
  end

  def user_posts
    user = User.find(params[:user_id])
    @posts = user.posts.limit(8).order('id DESC').page(params[:page]).per(8)
    @name = user.name
  end

  def category_posts
    category = Category.find(params[:category_id])
    @posts = category.posts.limit(8).order('id DESC').page(params[:page]).per(8)
    @name = category.name
  end

  def maker_posts
    maker = Maker.find(params[:maker_id])
    @posts = maker.posts.limit(8).order('id DESC').page(params[:page]).per(8)
    @name = maker.name
  end

  def search
    @posts = Post.search(params[:keyword]).limit(8).order('id DESC').page(params[:page]).per(8)
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :image, :category_id, :maker_id).merge(user_id: current_user.id)
  end
end

def move_to_index
  redirect_to action: :index unless user_signed_in?
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @posts = Post.limit(3).order('id DESC')
    # @post = Post.find(params[:id])
    # @category = Category.find(@post.category_id)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @posts = current_user.posts.page(params[:page]).per(8)
  end
  def edit
    
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else 
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.haml
= render 'shared/header'
.contents
  .contents__top
    .contents__top__title
      カテゴリーから探す
    .contents__top__category
      - @categories.each do |category|
        .producter
          = link_to category_posts_posts_path(category_id: category.id) do
            .producter__item-image
              = image_tag category.image, height: '100%', width: '100%', class: 'iamge10'
            .producter__item-body
              .producter__item-body__name
                = category.name
= render 'shared/footer'

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LookForDarts
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/makers/index.html.haml
= render 'shared/header'
.contents
  .contents__top
    .contents__top__title
      メーカーから探す
    .contents__top__maker
      .contents__top__maker__name
        - @makers.each do |maker|
          .maker
            = link_to maker_posts_posts_path(maker_id: maker.id) do
              .maker__item-image
                =image_tag maker.image, height: '100%', width: '100%', class: 'iamge10'
              .maker__item-body
                .maker__item-body__name
                  = maker.name
= render 'shared/footer'

app/views/posts/_post.html.haml
.products
  .products__item-image
    =link_to image_tag(post.image.to_s, height: '100%', width: '100%', class: 'iamge10'), "/posts/#{post.id}"
  .products__item-body
    .products__item-body__title
      = link_to  "/posts/#{post.id}" do
        = post.title
    .products__item-body__contents
      .products__item-body__contents__left
        .products__item-body__contents__left__menu
        %ul
          カテゴリー：
        %ul
          メーカー :
        %ul
          投稿者 :
      .products__item-body__contents__right
        .products__item-body__contents__right__link
          %li
            = link_to "#"  do
              = post.category.name
          %li
            = link_to "#"  do
              = post.maker.name
          %li
            = link_to post.user.name, user_posts_posts_path(user_id: post.user.id)

app/views/posts/category_posts.html.haml
= render 'shared/header'
.content
  .content__top
    .content__top__title
      = @name
      の投稿一覧
    .content__top__category
      - @posts.each do |post|
        .products
          .products__item-image
            =link_to image_tag(post.image.to_s, height: '100%', width: '100%', class: 'iamge10'), "/posts/#{post.id}"
          .products__item-body
            .products__item-body__title
              = link_to "/posts/#{post.id}" do
                = post.title
            .products__item-body__contents
              .products__item-body__contents__left
                .products__item-body__contents__left__menu
                  %ul
                    カテゴリー：
                  %ul
                    メーカー :
                  %ul
                    投稿者 :
              .products__item-body__contents__right
                .products__item-body__contents__right__link
                  %li
                    = link_to post.category.name, category_posts_posts_path(category_id: post.category.id)
                  %li
                    = link_to post.maker.name, maker_posts_posts_path(maker_id: post.maker.id)
                  %li
                    = link_to post.user.name, user_posts_posts_path(user_id: post.user.id)
      .paginate
        =paginate(@posts)
= render 'shared/footer'

app/views/posts/create.html.haml
= render 'shared/header'
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h3 投稿が完了しました。
= render 'shared/footer'

app/views/posts/destroy.html.haml
= render 'shared/header'
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h3 削除が完了しました。
    .account-page__index
      = link_to posts_path  do
        %h4 口コミ一覧へ戻る
= render 'shared/footer'

app/views/posts/edit.html.haml
= render 'shared/header'
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 編集
    .account-page__inner--right.user-form
      = form_for(@post) do |f|
        .field
          .field-label
            = f.label :タイトル
            %i (必須)
          .field-input
            = f.text_field :title, placeholder: "商品名（必須40文字まで）"
        .field
          .field-label
            = f.label :画像
            %i (必須)
        .field-input
          = f.file_field :image
        .field
          .field-label
            = f.label :ダーツ種類
            %i (必須)
          .field-Choose
            = f.collection_select(:category_id, Category.all, :id, :name,prompt: "カテゴリーを選択してください", class: "form")
        .field
          .field-label
            = f.label :メーカー
            %i (必須)
          .field-Choose
            = f.collection_select(:maker_id, Maker.all, :id, :name, prompt: "メーカーを選択してください", class: "form")
        .field
          .field-label
            = f.label :詳細
            %i (必須)
          .field-input
            = f.text_area :text, size: "30x5", placeholder: "使ってみた感想（必須）"
        .actions
          = f.submit "投稿", class: 'btn'
= render 'shared/footer'

app/views/posts/index.html.haml
= render 'shared/header'
.content
  .content__top
    .content__top__title
      口コミ一覧
    .content__top__search
      = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
        = form.submit "検索", class: "search-btn"
    .content__top__category
      - @posts.each do |post|
        .products
          .products__item-image
            =link_to image_tag(post.image.to_s, height: '100%', width: '100%', class: 'iamge10'), "/posts/#{post.id}"
          .products__item-body
            .products__item-body__title
              = link_to  "/posts/#{post.id}" do
                = post.title
            .products__item-body__contents
              .products__item-body__contents__left
                .products__item-body__contents__left__menu
                %ul
                  カテゴリー：
                %ul
                  メーカー :
                %ul
                  投稿者 :
              .products__item-body__contents__right
                .products__item-body__contents__right__link
                  %li
                    = link_to post.category.name, category_posts_posts_path(category_id: post.category.id)
                  %li
                    = link_to post.maker.name, maker_posts_posts_path(maker_id: post.maker.id)
                  %li
                    = link_to post.user.name, user_posts_posts_path(user_id: post.user.id)
      .paginate
        =paginate(@posts)
= render 'shared/footer'

app/views/posts/maker_posts.html.haml
= render 'shared/header'
.content
  .content__top
    .content__top__title
      = @name
      一覧
    .content__top__category
      - @posts.each do |post|
        .products
          .products__item-image
            =link_to image_tag(post.image.to_s, height: '100%', width: '100%', class: 'iamge10'), "/posts/#{post.id}"
          .products__item-body
            .products__item-body__title
              = link_to "/posts/#{post.id}" do
                = post.title
            .products__item-body__contents
              .products__item-body__contents__left
                .products__item-body__contents__left__menu
                  %ul
                    カテゴリー：
                  %ul
                    メーカー :
                  %ul
                    投稿者 :
              .products__item-body__contents__right
                .products__item-body__contents__right__link
                  %li
                    = link_to post.category.name, category_posts_posts_path(category_id: post.category.id)
                  %li
                    = link_to post.maker.name, maker_posts_posts_path(maker_id: post.maker.id)
                  %li
                    = link_to post.user.name, user_posts_posts_path(user_id: post.user.id)
      .paginate
        =paginate(@posts)
= render 'shared/footer'

app/views/posts/new.html.haml
= render 'shared/header'
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 口コミ投稿
    .account-page__inner--right.user-form
      = form_for(@post) do |f|
        .field
          .field-label
            = f.label :タイトル
            %i (必須)
          .field-input
            = f.text_field :title, placeholder: "商品名（必須40文字まで）"
        .field
          .field-label
            = f.label :画像
            %i (必須)
        .field-input
          = f.file_field :image
        .field
          .field-label
            = f.label :ダーツ種類
            %i (必須)
          .field-Choose
            = f.collection_select(:category_id, Category.all, :id, :name,prompt: "カテゴリーを選択してください", class: "form")
        .field
          .field-label
            = f.label :メーカー
            %i (必須)
          .field-Choose
            = f.collection_select(:maker_id, Maker.all, :id, :name, prompt: "メーカーを選択してください", class: "form")
        .field
          .field-label
            = f.label :詳細
            %i (必須)
          .field-input
            = f.text_area :text, size: "30x5", placeholder: "使ってみた感想（必須）"
        .actions
          = f.submit "投稿", class: 'btn'
= render 'shared/footer'

app/views/posts/search.html.haml
= render 'shared/header'
.content
  .content__top
    .content__top__title
      検索結果一覧
    .content__top__search
      = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
        = form.submit "検索", class: "search-btn"
    .content__top__category
      - @posts.each do |post|
        = render partial: "post", locals: { post: post }
      .paginate
        =paginate(@posts)
= render 'shared/footer'

app/views/posts/show.html.haml
= render 'shared/header'
.product
  .product__top
    .product__top__title
      投稿詳細
    .product__top__category
  .product__main
    .product__main__item
      .product__main__item__image
        = image_tag(@post.image.to_s, height: '100%', width: '100%')
      .product__main__item__name
        .product__main__item__name__title
          = link_to "#" do
            = @post.title
        .table
          %table
            %tr
              %th.name 投稿者
              %td
                = link_to @post.user.name, user_posts_posts_path(user_id: @post.user.id)
            %tr
              %th.category カテゴリー
              %td
                = link_to @post.category.name, category_posts_posts_path(category_id: @post.category.id)
            %tr
              %th.maker メーカー
              %td
                = link_to @post.maker.name, maker_posts_posts_path(maker_id: @post.maker.id)
            %tr
              %th.text 説明
              %td.text
                = simple_format(@post.text)
    - if user_signed_in? && current_user.id == @post.user_id
      .post
        .post__content
          = link_to "/posts/#{@post.id}/edit", method: :get do
            .post__content__create
              %h7
                編集
            = link_to "/posts/#{@post.id}", method: :delete do
              .post__content__destroy
                %h7
                  削除
  .comment
    .comment__main
      .comment__main__item
        - if current_user
          = form_with(model: [@post, @comment],local: true) do |form|
            = form.text_area :text, placeholder: "コメントする",rows:"4" 
            = form.submit "コメントする"
        - else
          %strong
            %p ※コメント投稿には新規登録/ログインが必要です※
      .comments
        .comments__title
          %h6 <コメント一覧>
      .message
        .message__main
          - if @comments
            - @comments.each do |comment|
              .message__main__content
                .message__main__content__left
                  = link_to comment.user.name, user_posts_posts_path(user_id: comment.user.id)
                .message__main__content__right
                  = simple_format(comment.text)
        .paginate
          =paginate(@comments)
= render 'shared/footer'

app/views/posts/update.html.haml
= render 'shared/header'
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__header
      %h3 更新が完了しました。
    .account-page__index
      = link_to posts_path  do
        %h4 口コミ一覧へ戻る
= render 'shared/footer'

app/views/posts/user_posts.html.haml
= render 'shared/header'
.content
  .content__top
    .content__top__title
      = @name
      さんの投稿一覧
    .content__top__category
      - @posts.each do |post|
        .products
          .products__item-image
            =link_to image_tag(post.image.to_s, height: '100%', width: '100%', class: 'iamge10'), "/posts/#{post.id}"
          .products__item-body
            .products__item-body__title
              = link_to "/posts/#{post.id}" do
                = post.title
            .products__item-body__contents
              .products__item-body__contents__left
                .products__item-body__contents__left__menu
                  %ul
                    カテゴリー：
                  %ul
                    メーカー :
                  %ul
                    投稿者 :
              .products__item-body__contents__right
                .products__item-body__contents__right__link
                  %li
                    = link_to post.category.name, category_posts_posts_path(category_id: post.category.id)
                  %li
                    = link_to post.maker.name, maker_posts_posts_path(maker_id: post.maker.id)
                  %li
                    = link_to post.user.name, user_posts_posts_path(user_id: post.user.id)
      .paginate
        =paginate(@posts)
= render 'shared/footer'

app/views/shared/_footer.html.haml
.footer
  %ul.contents
    %li.content
      .content__head
        LookForDartsについて
      %ul
        %li
          =link_to "#" ,class:"ebtn"do
            会社概要（運営会社）
        %li
          =link_to "#" ,class:"ebtn"do
            プライバシーポリシー
    %li.content
      .content__head
        LookForDartsで探す
      %ul
        %li
          =link_to posts_path ,class:"gbtn"do
            ダーツ
        %li
          =link_to makers_path ,class:"fbtn"do
            メーカー
        %li
          =link_to categories_path ,class:"fbtn"do
            カテゴリー
    %li.content
      .content__head
        ヘルプ＆ガイド
      %ul
        %li
          =link_to "#" ,class:"hbtn"do
            LookForDartsガイド
        %li
          =link_to "#" ,class:"jbtn"do
            お知らせ
  .footer__logo
    =link_to url="#" ,class:"jbtn"do
      %a
        = link_to root_path do
          LookForDarts
      %p
        ©️LookForDarts

app/views/shared/_header.html.haml
.header
  .header__main
    .header__main--top
      .header__main--top-icon
        = link_to root_path do
          LookForDarts
    .header__main--bottom
      .header__main--bottom-right
      .maker-name
        %ul
          %li
            %a
              ダーツを探す
              %span.caret
            %div
              %ul
                %li
                  = link_to posts_path  do
                    口コミから
                %li
                  = link_to categories_path do
                    カテゴリーから
                %li
                  = link_to makers_path do
                    メーカーから
      - if user_signed_in?
        .maker-name
          %ul
            %li
              %a
                = current_user.name
                %span.caret
              %div
                %ul
                  %li
                    = link_to edit_user_registration_path(current_user) do
                      ユーザー編集
                  %li
                    = link_to "/users/#{current_user.id}" do
                      投稿一覧
                  %li
                    = link_to destroy_user_session_path,method: :delete do
                      ログアウト
        .maker-name
          %ul
            %li
              %a
                = link_to new_post_path  do
                  口コミ投稿
      - else
        .maker-name
          %ul
            %li
              %a
                = link_to new_user_session_path do
                  ログイン
        .maker-name
          %ul
            %li
              %a
                = link_to new_user_registration_path do
                  新規登録

app/views/shared/_shop.html.haml
.app
  .app__main
    .app__main--top
      気になるダーツを探してみよう
    .app__main--midle
      おすすめオンラインショップ
    .app__main--bottom
      =link_to url="https://www.s-darts.com/" ,class:"cbtn"do
        = image_tag 'sdarts.jpg',  height: '80', width: '120', class: 'iamge3'
      =link_to url="https://www.dartshive.jp/" ,class:"cbtn" do
        = image_tag 'dartshive.jpg',  height: '80', width: '120', class: 'iamge3'
      =link_to url="https://www.tito-shop.com/" ,class:"cbtn" do
        = image_tag 'tito.jpg',  height: '80', width: '120', class: 'iamge3'
      =link_to url="http://www.natural-9.jp/shopbrand/n9/" ,class:"cbtn" do
        = image_tag 'nine.jpg',  height: '80', width: '120', class: 'iamge3'
      =link_to url="https://www.maximnet.co.jp/" ,class:"cbtn" do
        = image_tag 'maxim.jpg',  height: '80', width: '120', class: 'iamge3'

app/views/toppages/index.html.haml
= render 'shared/header'
.main
  .main__top
    .main__top--content
      %h2 お気に入りのダーツを共有しよう
.contain
  .contain__title
    .contain__title__text
      %h2 LookForDartsとは
      %h4 ダーツってたくさん種類があって迷いますよね？
      %h4 そんな方へのおすすめのダーツの口コミ共有サービスです。
  .main-page
    .product
      .product__new
        %h3 新着口コミ
    .products
      - @posts.each do |post|
        .products__item
          .products__item__image
            =link_to image_tag(post.image.to_s, height: '100%', width: '100%', class: 'iamge10'), "/posts/#{post.id}"
          .products__item__body
            .products__item__body__title 
              %a
                = link_to "/posts/#{post.id}" do
                  = post.title
            .products__item__body__contents
              .products__item__body__contents__left
                .products__item__body__contents__left__menu
                %ul
                  カテゴリー：
                %ul
                  メーカー :
                %ul
                  投稿者 :
              .products__item__body__contents__right
                .products__item__body__contents__right__link
                  %li
                    = link_to post.category.name, category_posts_posts_path(category_id: post.category.id)
                  %li
                    = link_to post.maker.name, maker_posts_posts_path(maker_id: post.maker.id)
                  %li
                    = link_to post.user.name, user_posts_posts_path(user_id: post.user.id)
  .menu
    .menu__content
      = link_to posts_path do
        .menu__content__btn
          %h8
            もっと見る
= render 'shared/shop'
= render 'shared/footer'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
= render 'shared/header'
.content
  .content__top
    .content__top__title
      = @name
      さんの投稿一覧
    .content__top__category
      - @posts.each do |post|
        .products
          .products__item-image
            =link_to image_tag(post.image.to_s, height: '100%', width: '100%', class: 'iamge10'), "/posts/#{post.id}"
          .products__item-body
            .products__item-body__title
              = link_to "/posts/#{post.id}" do
                = post.title
            .products__item-body__contents
              .products__item-body__contents__left
                .products__item-body__contents__left__menu
                  %ul
                    カテゴリー：
                  %ul
                    メーカー :
                  %ul
                    投稿者 :
              .products__item-body__contents__right
                .products__item-body__contents__right__link
                  %li
                    = link_to post.category.name, category_posts_posts_path(category_id: post.category.id)
                  %li
                    = link_to post.maker.name, maker_posts_posts_path(maker_id: post.maker.id)
                  %li
                    = link_to post.user.name, user_posts_posts_path(user_id: post.user.id)
      .paginate
        =paginate(@posts)
= render 'shared/footer'